version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.13.0-browsers

    working_directory: ~/udemy

    environment:
      NODE_ENV: test

    steps:
    - checkout

    - restore_cache:
        keys:
        - dependencies-{{ checksum "package.json" }}

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: dependencies-{{ checksum "package.json" }}

    - run: yarn build
    - run: yarn test --ci --no-cache

    - store_artifacts:
        path: ~/udemy/junit.xml
